spring:
  datasource:

    #url: jdbc:postgresql://localhost:5432/users
    url: jdbc:h2:file:./src/main/resources/database/users
    username: sa
    password: password

  flyway:
    enabled: true
    #url: jdbc:postgresql://localhost:5432/users
    url: jdbc:h2:file:./src/main/resources/database/users
    user: sa
    password: password
  h2:
    console:
      enabled: true
      path: /h2-console


jwt:
  secret-key: ZnJhbmNpc2NvYW5kcmVzc2FsYXNiYXJyYWxlcw==


